reg_div = {
    "Accra": ["Accra Metro div"],
    "Kasoa": ["Weija", "Kasoa div"],
    "Ga-Central": ["Amasaman", "Ga-Central div"],
    "Bibiani": ["Bibiani div", "Wiawso", "Essam Debiso"],
    "Bolga": ["Bolga div", "Walewale", "Navrongo", "Bawku"],
    "Cape Coast": ["Cape Coast div", "Asikuma", "Winneba", "Swedru", "Elmina", "Mankessim", "Assin Fosu"],
    "Goaso": ["Goaso div", "Kenyase", "Mim", "Tepa"],
    "Ho": ["Ho div", "Aflao", "Keta", "Akatsi"],
    "Hohoe": ["Kpando", "Hohoe div"],
    "Dambai": ["Nkwanta", "Krachi", "Dambai div"],
    "Kumasi South": ["Kumasi South div", "Bohyen"],
    "Koforidua": ["Koforidua div", "Akropong", "Suhum", "Odumase", "Nsawam"],
    "Oda": ["Donkorkrom", "Nkawkaw", "Asamankese", "Akim Oda div"],
    "Konongo": ["Agogo", "Konongo div", "Juaso", "Ejisu"],
    "Kumasi North": ["Kumasi North div", "Offinso", "Asokore Mampong"],
    "Madina": ["Madina div", "La Dadekotopon"],
    "Mampong": ["Mampong div", "Atebubu", "Ejura", "Effiduase"],
    "Nkawie": ["Nkawie div", "Mankranso"],
    "Obuasi": ["Dunkwa", "Obuasi div", "Subin", "Bekwai", "New Edubiase", "Ofoase Kokoben"],
    "Sunyani": ["Sampa", "Bechem", "Dormaa Ahenkro", "Berekum", "Sunyani div"],
    "Takoradi": ["Takoradi div", "Axim", "Half Assini"],
    "Tamale": ["Yendi", "Tamale div", "Buipe", "Salaga", "Damango"],
    "Tarkwa": ["Enchi", "Tarkwa div", "Asankragua"],
    "Techiman": ["Techiman div", "Nkoranza", "Wenchi", "Kintampo"],
    "Tema": ["Tema div", "Ashaiman", "Teshie-Nungua", "Ada"],
    "Wa": ["Bole", "Wa div", "Tumu"]
}

metro_list = [
    "Abeka",
    "Ablekuma",
    "Anyaa",
    "Lapaz",
    "Lartebiokorshie",
    "Accra New Town",
    "Odokor",
    "Dansoman",
    "Adabraka"
]